# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-03 06:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='T_BRAND',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=20, verbose_name='\u54c1\u724c\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u54c1\u724c\u7ba1\u7406',
                'verbose_name_plural': '\u54c1\u724c\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='T_COMMISION',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commision_name', models.CharField(max_length=20, verbose_name='\u63d0\u6210\u540d\u79f0')),
                ('commision_sum', models.IntegerField(verbose_name='\u63d0\u6210\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u63d0\u6210\u7ba1\u7406',
                'verbose_name_plural': '\u63d0\u6210\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='T_CUSTOMER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=20, verbose_name='\u5ba2\u6237\u59d3\u540d')),
                ('customer_phone', models.CharField(max_length=40, verbose_name='\u5ba2\u6237\u7535\u8bdd')),
                ('customer_addr', models.CharField(max_length=400, verbose_name='\u5ba2\u6237\u5730\u5740')),
                ('customer_model', models.CharField(max_length=40, null=True, verbose_name='\u5ba2\u6237\u6237\u578b')),
            ],
            options={
                'verbose_name': '\u5ba2\u6237\u7ba1\u7406',
                'verbose_name_plural': '\u5ba2\u6237\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='T_MODEL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=20, verbose_name='\u578b\u53f7\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u578b\u53f7\u7ba1\u7406',
                'verbose_name_plural': '\u578b\u53f7\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='T_SALESPERSON',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_name', models.CharField(max_length=20, verbose_name='\u8425\u4e1a\u5458\u59d3\u540d')),
                ('sales_phone', models.CharField(max_length=8, verbose_name='\u8425\u4e1a\u5458\u7535\u8bdd')),
                ('sales_commision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myoper.T_COMMISION', verbose_name='\u8425\u4e1a\u5458\u63d0\u6210')),
            ],
            options={
                'verbose_name': '\u8425\u4e1a\u5458\u7ba1\u7406',
                'verbose_name_plural': '\u8425\u4e1a\u5458\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='T_SUPPLIER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=20, verbose_name='\u4f9b\u5e94\u5546\u59d3\u540d')),
                ('supplier_phone', models.CharField(max_length=40, verbose_name='\u4f9b\u5e94\u5546\u7535\u8bdd')),
                ('supplier_email', models.EmailField(max_length=254, null=True, verbose_name='\u4f9b\u5e94\u5546\u7535\u5b50\u90ae\u4ef6')),
                ('supplier_brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myoper.T_BRAND', verbose_name='\u4f9b\u5e94\u5546\u54c1\u724c')),
            ],
            options={
                'verbose_name': '\u4f9b\u5e94\u5546\u7ba1\u7406',
                'verbose_name_plural': '\u4f9b\u5e94\u5546\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='T_TYPE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20, verbose_name='\u7c7b\u578b\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u7c7b\u578b\u7ba1\u7406',
                'verbose_name_plural': '\u7c7b\u578b\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='T_USER',
            fields=[
                ('user_id', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='\u767b\u9646ID')),
                ('user_name', models.CharField(max_length=20, verbose_name='\u7528\u6237\u540d')),
                ('user_password', models.CharField(max_length=100, verbose_name='\u7528\u6237\u5bc6\u7801')),
                ('user_status', models.CharField(default='0', max_length=1, verbose_name='\u7528\u6237\u72b6\u6001')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u8868',
                'verbose_name_plural': '\u7528\u6237\u8868',
            },
        ),
    ]
