# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-03 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myoper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_commision',
            name='commision_name',
            field=models.CharField(max_length=20, verbose_name='\u63d0\u6210\u6bd4\u4f8b'),
        ),
        migrations.AlterField(
            model_name='t_commision',
            name='commision_sum',
            field=models.IntegerField(verbose_name='\u63d0\u6210\u6bd4\u4f8b'),
        ),
    ]
