# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-04 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myoper', '0003_auto_20170603_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_WAREHOUSE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ware_name', models.CharField(max_length=20, verbose_name='\u4ed3\u5e93\u540d\u79f0')),
                ('ware_phone', models.CharField(max_length=40, verbose_name='\u4ed3\u5e93\u7535\u8bdd')),
                ('ware_addr', models.CharField(max_length=400, verbose_name='\u4ed3\u5e93\u5730\u5740')),
            ],
            options={
                'verbose_name': '\u4ed3\u5e93\u7ba1\u7406',
                'verbose_name_plural': '\u4ed3\u5e93\u7ba1\u7406',
            },
        ),
    ]
